# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12es7dnlS5qI8a-gg2IdTCIRDFuxGe6yB

# New Section
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
BosData = pd.read_csv('BostonHousing.csv')

# Features (11 regressors)
X = BosData.iloc[:, 0:11]

# Target variable (MEDV)
y = BosData.iloc[:, 13]
# Alternatively:
# y = BosData['MEDV']

# Boston Housing Dataset is derived from information collected by
# the US Census Service concerning housing in the Boston area.

# Split data into training and testing sets
Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2, random_state=5
)

# Create Linear Regression model
reg = LinearRegression()

# Train the model
reg.fit(Xtrain, ytrain)

# Predict on training data
ytrainpredict = reg.predict(Xtrain)

# Calculate training metrics
mse = mean_squared_error(ytrain, ytrainpredict)
r2 = r2_score(ytrain, ytrainpredict)

print('Train MSE =', mse)
print('Train R2 score =', r2)
print("\n")

# Predict on testing data
ytestpredict = reg.predict(Xtest)

# Calculate testing metrics
mse = mean_squared_error(ytest, ytestpredict)
r2 = r2_score(ytest, ytestpredict)

print('Test MSE =', mse)
print('Test R2 score =', r2)

# Plot Actual vs Predicted Values
plt.figure(figsize=(8, 6))
plt.scatter(ytest, ytestpredict, color='blue', alpha=0.6)

# Perfect prediction reference line
plt.plot(
    [ytest.min(), ytest.max()],
    [ytest.min(), ytest.max()],
    color='red',
    linestyle='--'
)

plt.title('Actual vs Predicted Values')
plt.xlabel('Actual MEDV')
plt.ylabel('Predicted MEDV')
plt.grid(True)
plt.show()